services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: expense-track-jrc
      - key: FIREBASE_PRIVATE_KEY_ID
        value: be73c9e4c7f9ff7987deb217b05621cf7bb67960
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCstA3+HYf1Wf/R\nSv45D+dNIEc9K1q26PQX2cAwhq+TN3pW/+vm9KbnkU4auNc4MJci9NHVKENSL6Q2\nOmdvsIn8Qr1jLOZRLUqiUxwQ0QSJx0s2a1VDH5gqfTKz2HxEegkQY2VFbCo/s8Fq\nMXpMzSbCm/EMdpCQWbkWgM5HckwTAyyZXWOkMo1Jg+2a8LVUP7Z60HFdsZAj0eIm\nBhSwYq74EMDKS0AjDQAz5c/+15/bReN2rzkFl5vtxiYbfE9S6RlZrxwbxuxlSer5\n4j8eSpSpySxAof1YRolBoNuzhvQnKz9pOONVJh+ga3xC07o2Igkz4MuH4H5HHeHE\nSNg8n3ePAgMBAAECggEACpSRUuMeRDK6UGkmv/owcnIqyx2P1irZYWiutIpb0UoR\nzaiqHCEa5I7rWQm/7apUaAjVnhh0X2GZztSvJ5GKMpEoJx5GEe0TaHRtAL69Z291\nNSVIOO+Dk/7Nj2UQ3+UWDxH3z1P8FqD9lXLoijH7UOrazqeo3Z8RjsZfXNMsw/FQ\n8y9tpVssalsoS6r+J4WBRq11+CcqkJk7hH4jJoWmLPRiwbBmkxAgDAWih/gLDB4D\nZS/946ly4Cp0TUTZ/lCwmDvRgwhYbdsi37NUqnZNncDGjJgcP6t4EYj8XvYWEH6p\nGiY8YPrU6A9n+q/VSYzi4dT7etiNjdkoEBgzuJLw+QKBgQDoM8ZEhQzkF37soiuh\n6dTA81gKt/L3szdQIYloY2AORhRPsI62129vHuiRnDkL0oiz9Equ1Q7hLLq1ycUk\nnbtvA3roBq7sWQeDE0lT3vpzjK2aAJUxsBa7LfQuuXSv3cOtoa2jXNgoi6vK+JJi\nco5BXjEDO1yoMfCpPVMd4EarxQKBgQC+ZzlXDcB8qBF1mgC0H8aIW9/oTEeCEySr\nSMwDrMq6iy8FyUKb0fqWPLuI4hrIkBl6iwofOIviHn9DMbKfgc6q2gj9YpKE6ao5\nz+KqvAgCworQlbPb7hYwllEvTrd4Nv7FsWW5jFgL8BD8NAPAXwPoj+CKJJk8AsSo\nmlOIMfenQwKBgQCZ2OP+tiDqZ17jLje2mZUrGpA02dgTohx97Rp7nYwhKPGAMzz7\njBX7DAGPqHBrktycTrnEyMmJC/fRRpRmRFPRo/6lCPiRBBPkFr044r4SHR1Qsh4n\nw8Hr1vC4nIvhkg96VWsUmAloI9J5MuTacYgra1sSBxzHG/+WQll1rAlm+QKBgASF\nRuM+PFe5VdDI+0NLjdcm90X4qan48mHutIlRzO5o55DnmmFAtwZiIsG5PJGOekxi\niLb9DLUtrC/YOjl3R4Te8F+zu27UbWo5+VO8ayRFoi4Zn8+U84nrx7mr0MdV5u6i\nq5ugLWb7KCwUwBINL3aSE+6zt7+pASpPn7QYG50pAoGBAOUS3JorlVlmGcWOyWNV\nXsNqNOYx8vPyicrz1y/O9iWF2nmei6UKlEDpsuJGl11vfuG1I4YVjV/fV01boGCS\nePJWsCRj19ItCLeNUiQNCBBpCiXPn0wJ4S81GRp4lcYsPWMPtBs8iYSBhgre13aT\n8yI6TgqKVbfpxSN+543uRmD+\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@expense-track-jrc.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: "109194256016806302266"
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token